#define POUND                            1
#define NOT                              2
#define LBRACKET                         3
#define RBRACKET                         4
#define IDENT                            5
#define EQ                               6
#define STRING_LIT                       7
#define LPAREN                           8
#define RPAREN                           9
#define COMMA                           10
